In [491]:
import pandas as pd

In [492]:
df = pd.read_csv("dist_keys.csv")

In [493]:
df.sort_values('District_Key')

             District_Key
0           AP_Anantapur
1             AP_Aravalli
2           AP_Chittoor
3             AP_Guntur
4              AP_Krishna
..                    ...
646     WB_Uttar Dinajpur
647  WB_south 24 parganas
648           agar  malwa
649         central delhi
650                   goa

[651 rows x 1 columns]

In [438]:
the_a = pd.read_csv("districts.csv")
# the_a.head()

In [507]:
the_b = the_a[["Date","District","Confirmed"]].copy()

In [510]:
date_df=the_b.loc[the_b['Date'] == "14-08-2021"]
date_df

              Date           District  Confirmed
306588  14-08-2021            Unknown       7548
306589  14-08-2021          Anantapur     156771
306590  14-08-2021           Chittoor     234871
306591  14-08-2021      East Godavari     282389
306592  14-08-2021   Foreign Evacuees        434
...            ...                ...        ...
307241  14-08-2021    Purba Bardhaman      40280
307242  14-08-2021    Purba Medinipur      61010
307243  14-08-2021            Purulia      19214
307244  14-08-2021  South 24 Parganas      96779
307245  14-08-2021     Uttar Dinajpur      19536

[658 rows x 3 columns]

In [496]:
the_c = pd.read_csv("cowin_vaccine_data_districtwise.csv")
# the_c.head()

c:\users\dell\appdata\local\programs\python\python39\lib\site-packages\IPython\core\interactiveshell.py:3169: DtypeWarning: Columns (6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,50,51,52,53,54,55,56,57,58,59,60,61,62,63,64,65,66,67,68,69,70,71,72,73,74,75,76,77,78,79,80,81,82,83,84,85,86,87,88,89,90,91,92,93,94,95,96,97,98,99,100,101,102,103,104,105,106,107,108,109,110,111,112,113,114,115,116,117,118,119,120,121,122,123,124,125,126,127,128,129,130,131,132,133,134,135,136,137,138,139,140,141,142,143,144,145,146,147,148,149,150,151,152,153,154,155,156,157,158,159,160,161,162,163,164,165,166,167,168,169,170,171,172,173,174,175,176,177,178,179,180,181,182,183,184,185,186,187,188,189,190,191,192,193,194,195,196,197,198,199,200,201,202,203,204,205,206,207,208,209,210,211,212,213,214,215,216,217,218,219,220,221,222,223,224,225,226,227,228,229,230,231,232,233,234,235,236,237,238,239,240,241,242,243,244,245,246,247,248,249,250,251,252,253,254,255,256,257,258,259,260,261,262,263,264,265,266,267,268,269,270,271,272,273,274,275,276,277,278,279,280,281,282,283,284,285,286,287,288,289,290,291,292,293,294,295,296,297,298,299,300,301,302,303,304,305,306,307,308,309,310,311,312,313,314,315,316,317,318,319,320,321,322,323,324,325,326,327,328,329,330,331,332,333,334,335,336,337,338,339,340,341,342,343,344,345,346,347,348,349,350,351,352,353,354,355,356,357,358,359,360,361,362,363,364,365,366,367,368,369,370,371,372,373,374,375,376,377,378,379,380,381,382,383,384,385,386,387,388,389,390,391,392,393,394,395,396,397,398,399,400,401,402,403,404,405,406,407,408,409,410,411,412,413,414,415,416,417,418,419,420,421,422,423,424,425,426,427,428,429,430,431,432,433,434,435,436,437,438,439,440,441,442,443,444,445,446,447,448,449,450,451,452,453,454,455,456,457,458,459,460,461,462,463,464,465,466,467,468,469,470,471,472,473,474,475,476,477,478,479,480,481,482,483,484,485,486,487,488,489,490,491,492,493,494,495,496,497,498,499,500,501,502,503,504,505,506,507,508,509,510,511,512,513,514,515,516,517,518,519,520,521,522,523,524,525,526,527,528,529,530,531,532,533,534,535,536,537,538,539,540,541,542,543,544,545,546,547,548,549,550,551,552,553,554,555,556,557,558,559,560,561,562,563,564,565,566,567,568,569,570,571,572,573,574,575,576,577,578,579,580,581,582,583,584,585,586,587,588,589,590,591,592,593,594,595,596,597,598,599,600,601,602,603,604,605,606,607,608,609,610,611,612,613,614,615,616,617,618,619,620,621,622,623,624,625,626,627,628,629,630,631,632,633,634,635,636,637,638,639,640,641,642,643,644,645,646,647,648,649,650,651,652,653,654,655,656,657,658,659,660,661,662,663,664,665,666,667,668,669,670,671,672,673,674,675,676,677,678,679,680,681,682,683,684,685,686,687,688,689,690,691,692,693,694,695,696,697,698,699,700,701,702,703,704,705,706,707,708,709,710,711,712,713,714,715,716,717,718,719,720,721,722,723,724,725,726,727,728,729,730,731,732,733,734,735,736,737,738,739,740,741,742,743,744,745,746,747,748,749,750,751,752,753,754,755,756,757,758,759,760,761,762,763,764,765,766,767,768,769,770,771,772,773,774,775,776,777,778,779,780,781,782,783,784,785,786,787,788,789,790,791,792,793,794,795,796,797,798,799,800,801,802,803,804,805,806,807,808,809,810,811,812,813,814,815,816,817,818,819,820,821,822,823,824,825,826,827,828,829,830,831,832,833,834,835,836,837,838,839,840,841,842,843,844,845,846,847,848,849,850,851,852,853,854,855,856,857,858,859,860,861,862,863,864,865,866,867,868,869,870,871,872,873,874,875,876,877,878,879,880,881,882,883,884,885,886,887,888,889,890,891,892,893,894,895,896,897,898,899,900,901,902,903,904,905,906,907,908,909,910,911,912,913,914,915,916,917,918,919,920,921,922,923,924,925,926,927,928,929,930,931,932,933,934,935,936,937,938,939,940,941,942,943,944,945,946,947,948,949,950,951,952,953,954,955,956,957,958,959,960,961,962,963,964,965,966,967,968,969,970,971,972,973,974,975,976,977,978,979,980,981,982,983,984,985,986,987,988,989,990,991,992,993,994,995,996,997,998,999,1000,1001,1002,1003,1004,1005,1006,1007,1008,1009,1010,1011,1012,1013,1014,1015,1016,1017,1018,1019,1020,1021,1022,1023,1024,1025,1026,1027,1028,1029,1030,1031,1032,1033,1034,1035,1036,1037,1038,1039,1040,1041,1042,1043,1044,1045,1046,1047,1048,1049,1050,1051,1052,1053,1054,1055,1056,1057,1058,1059,1060,1061,1062,1063,1064,1065,1066,1067,1068,1069,1070,1071,1072,1073,1074,1075,1076,1077,1078,1079,1080,1081,1082,1083,1084,1085,1086,1087,1088,1089,1090,1091,1092,1093,1094,1095,1096,1097,1098,1099,1100,1101,1102,1103,1104,1105,1106,1107,1108,1109,1110,1111,1112,1113,1114,1115,1116,1117,1118,1119,1120,1121,1122,1123,1124,1125,1126,1127,1128,1129,1130,1131,1132,1133,1134,1135,1136,1137,1138,1139,1140,1141,1142,1143,1144,1145,1146,1147,1148,1149,1150,1151,1152,1153,1154,1155,1156,1157,1158,1159,1160,1161,1162,1163,1164,1165,1166,1167,1168,1169,1170,1171,1172,1173,1174,1175,1176,1177,1178,1179,1180,1181,1182,1183,1184,1185,1186,1187,1188,1189,1190,1191,1192,1193,1194,1195,1196,1197,1198,1199,1200,1201,1202,1203,1204,1205,1206,1207,1208,1209,1210,1211,1212,1213,1214,1215,1216,1217,1218,1219,1220,1221,1222,1223,1224,1225,1226,1227,1228,1229,1230,1231,1232,1233,1234,1235,1236,1237,1238,1239,1240,1241,1242,1243,1244,1245,1246,1247,1248,1249,1250,1251,1252,1253,1254,1255,1256,1257,1258,1259,1260,1261,1262,1263,1264,1265,1266,1267,1268,1269,1270,1271,1272,1273,1274,1275,1276,1277,1278,1279,1280,1281,1282,1283,1284,1285,1286,1287,1288,1289,1290,1291,1292,1293,1294,1295,1296,1297,1298,1299,1300,1301,1302,1303,1304,1305,1306,1307,1308,1309,1310,1311,1312,1313,1314,1315,1316,1317,1318,1319,1320,1321,1322,1323,1324,1325,1326,1327,1328,1329,1330,1331,1332,1333,1334,1335,1336,1337,1338,1339,1340,1341,1342,1343,1344,1345,1346,1347,1348,1349,1350,1351,1352,1353,1354,1355,1356,1357,1358,1359,1360,1361,1362,1363,1364,1365,1366,1367,1368,1369,1370,1371,1372,1373,1374,1375,1376,1377,1378,1379,1380,1381,1382,1383,1384,1385,1386,1387,1388,1389,1390,1391,1392,1393,1394,1395,1396,1397,1398,1399,1400,1401,1402,1403,1404,1405,1406,1407,1408,1409,1410,1411,1412,1413,1414,1415,1416,1417,1418,1419,1420,1421,1422,1423,1424,1425,1426,1427,1428,1429,1430,1431,1432,1433,1434,1435,1436,1437,1438,1439,1440,1441,1442,1443,1444,1445,1446,1447,1448,1449,1450,1451,1452,1453,1454,1455,1456,1457,1458,1459,1460,1461,1462,1463,1464,1465,1466,1467,1468,1469,1470,1471,1472,1473,1474,1475,1476,1477,1478,1479,1480,1481,1482,1483,1484,1485,1486,1487,1488,1489,1490,1491,1492,1493,1494,1495,1496,1497,1498,1499,1500,1501,1502,1503,1504,1505,1506,1507,1508,1509,1510,1511,1512,1513,1514,1515,1516,1517,1518,1519,1520,1521,1522,1523,1524,1525,1526,1527,1528,1529,1530,1531,1532,1533,1534,1535,1536,1537,1538,1539,1540,1541,1542,1543,1544,1545,1546,1547,1548,1549,1550,1551,1552,1553,1554,1555,1556,1557,1558,1559,1560,1561,1562,1563,1564,1565,1566,1567,1568,1569,1570,1571,1572,1573,1574,1575,1576,1577,1578,1579,1580,1581,1582,1583,1584,1585,1586,1587,1588,1589,1590,1591,1592,1593,1594,1595,1596,1597,1598,1599,1600,1601,1602,1603,1604,1605,1606,1607,1608,1609,1610,1611,1612,1613,1614,1615,1616,1617,1618,1619,1620,1621,1622,1623,1624,1625,1626,1627,1628,1629,1630,1631,1632,1633,1634,1635,1636,1637,1638,1639,1640,1641,1642,1643,1644,1645,1646,1647,1648,1649,1650,1651,1652,1653,1654,1655,1656,1657,1658,1659,1660,1661,1662,1663,1664,1665,1666,1667,1668,1669,1670,1671,1672,1673,1674,1675,1676,1677,1678,1679,1680,1681,1682,1683,1684,1685,1686,1687,1688,1689,1690,1691,1692,1693,1694,1695,1696,1697,1698,1699,1700,1701,1702,1703,1704,1705,1706,1707,1708,1709,1710,1711,1712,1713,1714,1715,1716,1717,1718,1719,1720,1721,1722,1723,1724,1725,1726,1727,1728,1729,1730,1731,1732,1733,1734,1735,1736,1737,1738,1739,1740,1741,1742,1743,1744,1745,1746,1747,1748,1749,1750,1751,1752,1753,1754,1755,1756,1757,1758,1759,1760,1761,1762,1763,1764,1765,1766,1767,1768,1769,1770,1771,1772,1773,1774,1775,1776,1777,1778,1779,1780,1781,1782,1783,1784,1785,1786,1787,1788,1789,1790,1791,1792,1793,1794,1795,1796,1797,1798,1799,1800,1801,1802,1803,1804,1805,1806,1807,1808,1809,1810,1811,1812,1813,1814,1815,1816,1817,1818,1819,1820,1821,1822,1823,1824,1825,1826,1827,1828,1829,1830,1831,1832,1833,1834,1835,1836,1837,1838,1839,1840,1841,1842,1843,1844,1845,1846,1847,1848,1849,1850,1851,1852,1853,1854,1855,1856,1857,1858,1859,1860,1861,1862,1863,1864,1865,1866,1867,1868,1869,1870,1871,1872,1873,1874,1875,1876,1877,1878,1879,1880,1881,1882,1883,1884,1885,1886,1887,1888,1889,1890,1891,1892,1893,1894,1895,1896,1897,1898,1899,1900,1901,1902,1903,1904,1905,1906,1907,1908,1909,1910,1911,1912,1913,1914,1915,1916,1917,1918,1919,1920,1921,1922,1923,1924,1925,1926,1927,1928,1929,1930,1931,1932,1933,1934,1935,1936,1937,1938,1939,1940,1941,1942,1943,1944,1945,1946,1947,1948,1949,1950,1951,1952,1953,1954,1955,1956,1957,1958,1959,1960,1961,1962,1963,1964,1965,1966,1967,1968,1969,1970,1971,1972,1973,1974,1975,1976,1977,1978,1979,1980,1981,1982,1983,1984,1985,1986,1987,1988,1989,1990,1991,1992,1993,1994,1995,1996,1997,1998,1999,2000,2001,2002,2003,2004,2005,2006,2007,2008,2009,2010,2011,2012,2013,2014,2015,2016,2017,2018,2019,2020,2021,2022,2023,2024,2025,2026,2027,2028,2029,2030,2031,2032,2033,2034,2035,2036,2037,2038,2039,2040,2041,2042,2043,2044,2045,2046,2047,2048,2049,2050,2051,2052,2053,2054,2055,2056,2057,2058,2059,2060,2061,2062,2063,2064,2065,2066,2067,2068,2069,2070,2071,2072,2073,2074,2075,2076,2077,2078,2079,2080,2081,2082,2083,2084,2085,2086,2087,2088,2089,2090,2091,2092,2093,2094,2095,2096,2097,2098,2099,2100,2101,2102,2103,2104,2105,2106,2107,2108,2109,2110,2111,2112,2113,2114,2115,2116,2117,2118,2119,2120,2121,2122,2123,2124,2125,2126,2127,2128,2129,2130,2131,2132,2133,2134,2135,2136,2137,2138,2139,2140,2141,2142,2143,2144,2145,2146,2147,2148,2149,2150,2151,2152,2153,2154,2155,2156,2157,2158,2159,2160,2161,2162,2163,2164,2165,2166,2167,2168,2169,2170,2171,2172,2173,2174,2175,2176,2177,2178,2179,2180,2181,2182,2183,2184,2185,2186,2187,2188,2189,2190,2191,2192,2193,2194,2195,2196,2197,2198,2199,2200,2201,2202,2203,2204,2205,2206,2207,2208,2209,2210,2211,2212,2213,2214,2215,2216,2217,2218,2219,2220,2221,2222,2223,2224,2225,2226,2227,2228,2229,2230,2231,2232,2233,2234,2235,2236,2237,2238,2239,2240,2241,2242,2243,2244,2245,2246,2247,2248,2249,2250,2251,2252,2253,2254,2255,2256,2257,2258,2259,2260,2261,2262,2263,2264,2265,2266,2267,2268,2269,2270,2271,2272,2273,2274,2275,2276,2277,2278,2279,2280,2281,2282,2283,2284,2285,2286,2287,2288,2289,2290,2291,2292,2293,2294,2295,2296,2297,2298,2299,2300,2301,2302,2303,2304,2305,2306,2307,2308,2309,2310,2311,2312,2313,2314,2315,2316,2317,2318,2319,2320,2321,2322,2323,2324,2325,2326,2327,2328,2329,2330,2331,2332,2333,2334,2335,2336,2337,2338,2339,2340,2341,2342,2343,2344,2345,2346,2347,2348,2349,2350,2351,2352,2353,2354,2355,2356,2357,2358,2359,2360,2361,2362,2363,2364,2365,2366,2367,2368,2369,2370,2371,2372,2373,2374,2375,2376,2377,2378,2379,2380,2381,2382,2383,2384,2385,2386,2387,2388,2389,2390,2391,2392,2393,2394,2395,2396,2397,2398,2399,2400,2401,2402,2403,2404,2405,2406,2407,2408,2409,2410,2411,2412,2413,2414,2415,2416,2417,2418,2419,2420,2421,2422,2423,2424,2425,2426,2427,2428,2429,2430,2431,2432,2433,2434,2435,2436,2437,2438,2439,2440,2441,2442,2443,2444,2445,2446,2447,2448,2449,2450,2451,2452,2453,2454,2455,2456,2457,2458,2459,2460,2461,2462,2463,2464,2465,2466,2467,2468,2469,2470,2471,2472,2473,2474,2475,2476,2477,2478,2479,2480,2481,2482,2483,2484,2485,2486,2487,2488,2489,2490,2491,2492,2493,2494,2495,2496,2497,2498,2499,2500,2501,2502,2503,2504,2505,2506,2507,2508,2509,2510,2511,2512,2513,2514,2515,2516,2517,2518,2519,2520,2521,2522,2523,2524,2525,2526,2527,2528,2529,2530,2531,2532,2533,2534,2535,2536,2537,2538,2539,2540,2541,2542,2543,2544,2545,2546,2547,2548,2549,2550,2551,2552,2553,2554,2555,2556,2557,2558,2559,2560,2561,2562,2563,2564,2565,2566,2567,2568,2569,2570,2571,2572,2573,2574,2575,2576,2577,2578,2579,2580,2581,2582,2583,2584,2585,2586,2587,2588,2589,2590,2591,2592,2593,2594,2595,2596,2597,2598,2599,2600,2601,2602,2603,2604,2605,2606,2607,2608,2609,2610,2611,2612,2613,2614,2615,2616,2617,2618,2619,2620,2621,2622,2623,2624,2625,2626,2627,2628,2629,2630,2631,2632,2633,2634,2635,2636,2637,2638,2639,2640,2641,2642,2643,2644,2645,2646,2647,2648,2649,2650,2651,2652,2653,2654,2655,2656,2657,2658,2659,2660,2661,2662,2663,2664,2665,2666,2667,2668,2669,2670,2671,2672,2673,2674,2675,2676,2677,2678,2679,2680,2681,2682,2683,2684,2685,2686,2687,2688,2689,2690,2691,2692,2693,2694,2695,2696,2697,2698,2699,2700,2701,2702,2703,2704,2705,2706,2707,2708,2709,2710,2711,2712,2713,2714,2715,2716,2717,2718,2719,2720,2721,2722,2723,2724,2725,2726,2727,2728,2729,2730,2731,2732,2733,2734,2735,2736,2737,2738,2739,2740,2741,2742,2743,2744,2745,2746,2747,2748,2749,2750,2751,2752,2753,2754,2755,2756,2757,2758,2759,2760,2761,2762,2763,2764,2765,2766,2767,2768,2769,2770,2771,2772,2773,2774,2775,2776,2777,2778,2779,2780,2781,2782,2783,2784,2785,2786,2787,2788,2789,2790,2791,2792,2793,2794,2795,2796,2797,2798,2799,2800,2801,2802,2803,2804,2805,2806,2807,2808,2809,2810,2811,2812,2813,2814,2815,2816,2817,2818,2819,2820,2821,2822,2823,2824,2825,2826,2827,2828,2829,2830,2831,2832,2833,2834,2835,2836,2837,2838,2839,2840,2841,2842,2843,2844,2845,2846,2847,2848,2849,2850,2851,2852,2853,2854,2855,2856,2857,2858,2859,2860,2861,2862,2863,2864,2865,2866,2867,2868,2869,2870,2871,2872,2873,2874,2875,2876,2877,2878,2879,2880,2881,2882,2883,2884,2885,2886,2887,2888,2889,2890,2891,2892,2893,2894,2895) have mixed types.Specify dtype option on import or set low_memory=False.
  has_raised = await self.run_ast_nodes(code_ast.body, cell_name,

In [497]:
the_d= the_c[["District_Key","District"]].copy()
the_d.sort_values('District_Key')

                    District_Key                  District
1                    AN_Nicobars                  Nicobars
2    AN_North and Middle Andaman  North and Middle Andaman
3               AN_South Andaman             South Andaman
4                   AP_Anantapur                 Anantapur
5                    AP_Chittoor                  Chittoor
..                           ...                       ...
750                   WB_Purulia                   Purulia
735         WB_South 24 Parganas         South 24 Parganas
752         WB_South 24 Parganas         South 24 Parganas
753            WB_Uttar Dinajpur            Uttar Dinajpur
0                            NaN                       NaN

[755 rows x 2 columns]

In [498]:
int_df = pd.merge(df, the_d, how ='inner', on =['District_Key'])
tot_cases = pd.merge(int_df, the_b, how ='inner', on =['District'])
# int_df

In [499]:

dict = {'District_Key': 'districtid',
        'District': 'timeid',
        'Confirmed': 'cases'}
tot_cases.rename(columns=dict,inplace=True)
tot_cases['timeid']='overall'
# tot_cases.to_csv("cases-overall.csv",index=None,)

In [500]:
unique_districts=tot_cases['districtid'].unique()
cases_sum=[]
for i in unique_districts:
    cases_sum.append(tot_cases.loc[tot_cases['districtid'] == i, 'cases'].sum())

In [501]:
df2=pd.DataFrame(unique_districts)
dict1 = {0: 'districtid'}
df2.rename(columns=dict1,inplace=True,)
# df2

In [502]:
df1 = pd.DataFrame(cases_sum)
dict = {0: 'cases'}
df1.rename(columns=dict,inplace=True,)
# df1

In [503]:
new_d=[]
txt='overall'
for i in range(273):
    new_d.append(txt)
df3 = pd.DataFrame(new_d)
dicta = {0: 'timeid'}
df3.rename(columns=dicta,inplace=True,)
# df3

In [504]:
result = pd.concat([df2, df3], axis=1, join='inner')
final_result = pd.concat([result, df1], axis=1, join='inner')

In [506]:
update_df = final_result.drop(38)
update_df.to_csv('cases-overall.csv')
update_df

                 districtid   timeid      cases
0                AP_Krishna  overall   23434540
1                AP_Kurnool  overall   30581010
2               AP_Prakasam  overall   29432947
3             AP_Srikakulam  overall   25641221
4                  AR_Kamle  overall      38791
5              AR_Kra Daadi  overall      29817
6           AR_Kurung Kumey  overall      69403
7              AR_Lepa Rada  overall     128590
8                  AR_Lohit  overall     351193
9               AR_Longding  overall     119496
10           AR_Lower Siang  overall     134096
11                AR_Namsai  overall     285203
12         AR_Pakke Kessang  overall      64779
13                 AR_Tirap  overall     234873
14           AR_Upper Siang  overall     161437
15             AS_Dibrugarh  overall          0
16              AS_Udalguri  overall          0
17             BR_Darbhanga  overall    2328415
18                  BR_Gaya  overall    6254211
19             BR_Jehanabad  overall    2463022
20               BR_Katihar  overall    3986496
21            BR_Kishanganj  overall    2233435
22            BR_Lakhisarai  overall    1860181
23             BR_Madhepura  overall    2671468
24                BR_Munger  overall    2917468
25           BR_Muzaffarpur  overall    6692012
26               BR_Nalanda  overall    4892596
27                BR_Nawada  overall    2307152
28                 BR_Patna  overall   29950452
29                BR_Purnia  overall    5172854
30                BR_Rohtas  overall    3467995
31               BR_Saharsa  overall    3775274
32            BR_Samastipur  overall    3738036
33                 BR_Saran  overall    4673024
34            BR_Sheikhpura  overall    1695911
35               BR_Sheohar  overall     890799
36             BR_Sitamarhi  overall    2195914
37                CT_Bastar  overall    4273024
39                  CT_Durg  overall   18389730
40            CT_Kabeerdham  overall    4116200
41             CT_Kondagaon  overall    2593611
42                 CT_Korba  overall   10105472
43                CT_Koriya  overall    4292511
44            CT_Mahasamund  overall    5720028
45               CT_Mungeli  overall    3836493
46            CT_Narayanpur  overall     911177
47               CT_Raigarh  overall   12277551
48                CT_Raipur  overall   33008717
49           CT_Rajnandgaon  overall   11342723
50              CT_Surajpur  overall    4734460
51               CT_Surguja  overall    5745992
52   CT_Uttar Bastar Kanker  overall    4249273
53                   DN_Diu  overall     225658
54             GJ_Ahmedabad  overall   91991620
55           GJ_Banaskantha  overall    2682929
56                 GJ_Dahod  overall    1948082
57              GJ_Jamnagar  overall   13442780
58                 GJ_Kutch  overall    2499804
59             GJ_Mahisagar  overall    1468616
60                 GJ_Morbi  overall    1523446
61               GJ_Narmada  overall    1200130
62               GJ_Navsari  overall    1285248
63                 GJ_Patan  overall    2376146
64             GJ_Porbandar  overall     569558
65                GJ_Rajkot  overall   23932304
66           GJ_Sabarkantha  overall    1770838
67                 GJ_Surat  overall   61327632
68         GJ_Surendranagar  overall    1799869
69               HP_Kinnaur  overall     625492
70                 HP_Kullu  overall    1896519
71      HP_Lahaul and Spiti  overall     563131
72                 HP_Mandi  overall    5107083
73                HP_Shimla  overall    4897397
74                 HP_Solan  overall    4131212
75         HR_Charkhi Dadri  overall     921507
76               HR_Jhajjar  overall    3532354
77           HR_Kurukshetra  overall    4785277
78                   HR_Nuh  overall    1013525
79                HR_Palwal  overall    2296062
80             HR_Panchkula  overall    6160945
81               HR_Panipat  overall    6325626
82                HR_Rewari  overall    4930895
83                 HR_Sirsa  overall    5227845
84               HR_Sonipat  overall    9190861
85           HR_Yamunanagar  overall    4552543
86                JH_Chatra  overall    1097408
87                 JH_Dumka  overall     928704
88               JH_Giridih  overall    1946321
89            JH_Hazaribagh  overall    3489326
90               JH_Latehar  overall    1428559
91                 JH_Pakur  overall     543358
92                JH_Palamu  overall    2344909
93             JH_Sahibganj  overall    1005412
94               JH_Simdega  overall    1383910
95             JK_Baramulla  overall    4698309
96                  JK_Doda  overall    1551278
97              JK_Kishtwar  overall    1102589
98                JK_Kulgam  overall    2047339
99               JK_Kupwara  overall    2931171
100              JK_Pulwama  overall    3113368
101                JK_Punch  overall    1280851
102              JK_Rajouri  overall    2143090
103               JK_Ramban  overall    1165915
104                JK_Reasi  overall    1097138
105                JK_Samba  overall    1476943
106      KA_Chikkaballapura  overall    8113905
107       KA_Chikkamagaluru  overall    8477163
108          KA_Chitradurga  overall    7224479
109               KA_Hassan  overall   18314722
110               KA_Haveri  overall    5158765
111               KA_Kodagu  overall    4959709
112                KA_Kolar  overall    7480227
113               KA_Koppal  overall    7459223
114              KA_Raichur  overall    8258291
115           KA_Ramanagara  overall    4590541
116           KA_Shivamogga  overall   12648127
117                KA_Udupi  overall   13711543
118               KA_Yadgir  overall    5957641
119            KL_Alappuzha  overall   38424172
120            KL_Kasaragod  overall   17226347
121               KL_Kollam  overall   43243800
122             KL_Kottayam  overall   37821108
123            KL_Kozhikode  overall   61163508
124                  LA_Leh  overall    3592736
125             MH_Bhandara  overall   10844105
126                MH_Dhule  overall   10158005
127               MH_Gondia  overall    8244887
128              MH_Hingoli  overall    3469329
129                MH_Jalna  overall   11077572
130                MH_Latur  overall   17690509
131               MH_Nanded  overall   17873478
132            MH_Nandurbar  overall    7527265
133               MH_Nashik  overall   80605367
134            MH_Osmanabad  overall   11933926
135              MH_Palghar  overall   28095160
136             MH_Parbhani  overall    8732514
137                 MH_Pune  overall  235646606
138               MH_Sangli  overall   31520712
139           MH_Sindhudurg  overall    6273485
140              MH_Solapur  overall   35423238
141                MH_Thane  overall  143525933
142             MH_Yavatmal  overall   13326176
143               ML_Ribhoi  overall    1022278
144            MP_Burhanpur  overall     599200
145                MP_Datia  overall    1311296
146                MP_Harda  overall    1083062
147             MP_Jabalpur  overall   10086719
148               MP_Jhabua  overall    1543161
149                MP_Katni  overall    1709436
150             MP_Khargone  overall    2994443
151               MP_Mandla  overall     934459
152             MP_Mandsaur  overall    1715688
153          MP_Narsinghpur  overall    2212037
154              MP_Neemuch  overall    1728614
155               MP_Raisen  overall    1718187
156              MP_Rajgarh  overall    1639591
157               MP_Ratlam  overall    3221444
158                 MP_Rewa  overall    2915372
159                MP_Sagar  overall    3236813
160              MP_Shahdol  overall    1944099
161             MP_Shivpuri  overall    2356788
162            MP_Singrauli  overall    1521445
163               MP_Umaria  overall    1071271
164             MZ_Champhai  overall      72568
165              MZ_Kolasib  overall     331461
166            MZ_Lawngtlai  overall     279235
167                MZ_Mamit  overall     111888
168             MZ_Serchhip  overall     124468
169               NL_Kohima  overall    1765972
170             NL_Longleng  overall      25594
171           NL_Mokokchung  overall     199959
172                  NL_Mon  overall     266699
173                NL_Peren  overall     219802
174                 NL_Phek  overall      56395
175             OR_Balangir  overall    4646160
176              OR_Bargarh  overall    5918217
177              OR_Cuttack  overall   15895678
178            OR_Dhenkanal  overall    3283036
179        OR_Jagatsinghpur  overall    4687755
180           OR_Kendrapara  overall    4441450
181              OR_Khordha  overall   28899742
182              OR_Koraput  overall    3965141
183           OR_Malkangiri  overall    2465441
184           OR_Mayurbhanj  overall    7273631
185         OR_Nabarangapur  overall    3985098
186             OR_Nayagarh  overall    3919658
187              OR_Nuapada  overall    4398440
188             OR_Rayagada  overall    4282843
189            OR_Sambalpur  overall    5754784
190             PB_Amritsar  overall    9464971
191              PB_Barnala  overall    1277505
192             PB_Bathinda  overall    7142044
193             PB_Ludhiana  overall   17073985
194                PB_Mansa  overall    2410274
195                 PB_Moga  overall    1758446
196            PB_Pathankot  overall    3548815
197              PB_Patiala  overall   10004818
198             PB_Rupnagar  overall    2414893
199              PB_Sangrur  overall    3024871
200                 PY_Mahe  overall     945133
201           PY_Puducherry  overall   18299611
202                RJ_Ajmer  overall    8286992
203                RJ_Alwar  overall   12132777
204             RJ_Banswara  overall    1764504
205                RJ_Churu  overall    2966952
206                RJ_Dausa  overall    2156306
207            RJ_Jhunjhunu  overall    2729639
208              RJ_Karauli  overall    1240657
209                 RJ_Kota  overall   11387948
210               RJ_Nagaur  overall    4275707
211                 RJ_Pali  overall    5860320
212       RJ_Sawai Madhopur  overall    1779918
213                RJ_Sikar  overall    5721241
214               RJ_Sirohi  overall    2587617
215              RJ_Udaipur  overall    9596912
216             TN_Ariyalur  overall    2876964
217         TN_Kancheepuram  overall   15625291
218                TN_Karur  overall    3682666
219          TN_Krishnagiri  overall    6409037
220              TN_Madurai  overall   13937135
221         TN_Nagapattinam  overall    4823934
222           TN_Perambalur  overall    1787492
223          TN_Pudukkottai  overall   11957218
224            TN_Sivaganga  overall    3757126
225                TN_Theni  overall    9295419
226          TN_Thiruvallur  overall   48300170
227           TN_Thiruvarur  overall    6813355
228         TN_Thoothukkudi  overall   21078726
229          TN_Tirunelveli  overall    9605139
230             TN_Tiruppur  overall   13059533
231              TN_Vellore  overall   10658473
232               TR_Gomati  overall    1713253
233               TR_Khowai  overall     891814
234              TR_Unokoti  overall    1382403
235              UP_Aligarh  overall    5294707
236       UP_Ambedkar Nagar  overall    1082250
237             UP_Bahraich  overall    2438938
238            UP_Balrampur  overall    4611360
239                UP_Basti  overall    2717208
240          UP_Bulandshahr  overall    3901287
241           UP_Chitrakoot  overall    1401505
242                 UP_Etah  overall    1847804
243          UP_Farrukhabad  overall    2350242
244            UP_Gorakhpur  overall   12478253
245             UP_Hamirpur  overall    3385438
246                UP_Hapur  overall    2581120
247               UP_Hardoi  overall    3154645
248               UP_Jalaun  overall    2347110
249           UP_Kushinagar  overall    3309016
250             UP_Lalitpur  overall    2435983
251          UP_Maharajganj  overall    2932323
252               UP_Meerut  overall   13332592
253             UP_Mirzapur  overall    2246672
254            UP_Moradabad  overall    7730186
255        UP_Muzaffarnagar  overall    5726743
256             UP_Pilibhit  overall    2372043
257           UP_Pratapgarh  overall    4423696
258           UP_Rae Bareli  overall    3376978
259               UP_Rampur  overall    2845311
260           UP_Saharanpur  overall    6335943
261              UP_Sambhal  overall    1973390
262     UP_Sant Kabir Nagar  overall    1862964
263         UP_Shahjahanpur  overall    4211112
264               UP_Shamli  overall    2416101
265            UP_Shrawasti  overall     871263
266            UP_Sonbhadra  overall    3253886
267            UP_Sultanpur  overall    3055926
268                UP_Unnao  overall    2993709
269            UT_Bageshwar  overall     981912
270             UT_Haridwar  overall    9549308
271             UT_Nainital  overall    7316949
272          UT_Pithoragarh  overall    1794350