In [1]:
import pandas as pd
import numpy as np

In [2]:
data = pd.read_csv('cowin_vaccine_data_districtwise.csv',low_memory=False)

In [3]:
data = data.rename(columns = data.iloc[0])

In [4]:
data = data.drop(['S No','District_Key','Cowin Key'],axis=1)

In [5]:
data1 = data[['State_Code','State','Covaxin (Doses Administered)','CoviShield (Doses Administered)']].copy()

In [6]:
data1 = data1.iloc[1:,:]

In [7]:
cols = []
count = 1
for column in data1.columns:
    if column == 'Covaxin (Doses Administered)':
        cols.append(f'Covaxin (Doses Administered){count}')
        count+=1
        continue
    cols.append(column)
data1.columns = cols

In [8]:
colsa = []
count = 1
for column in data1.columns:
    if column == 'CoviShield (Doses Administered)':
        colsa.append(f'CoviShield (Doses Administered){count}')
        count+=1
        continue
    colsa.append(column)
data1.columns = colsa

In [9]:
df2 = data1.filter(regex='Covaxin ')
df3 = data1.filter(regex='CoviShield ')

In [10]:
newstuff = data1[['State_Code','State']].copy()

In [11]:
val1 = pd.concat([newstuff, df2], axis=1)
val2 = pd.concat([newstuff, df3], axis=1)

In [12]:
col_list= list(val1)
col_list.remove('State_Code')
col_list.remove('State')
# col_list

In [13]:
def sum_frame_by_column(frame, new_col_name, list_of_cols_to_sum):
    frame[new_col_name] = frame[list_of_cols_to_sum].astype(float).sum(axis=1)
    return(frame)

In [14]:
sum_frame_by_column(val1, 'covaxindoses', col_list)

,State_Code,State,Covaxin (Doses Administered)1,Covaxin (Doses Administered)2,Covaxin (Doses Administered)3,Covaxin (Doses Administered)4,Covaxin (Doses Administered)5,Covaxin (Doses Administered)6,Covaxin (Doses Administered)7,Covaxin (Doses Administered)8,...,Covaxin (Doses Administered)221,Covaxin (Doses Administered)222,Covaxin (Doses Administered)223,Covaxin (Doses Administered)224,Covaxin (Doses Administered)225,Covaxin (Doses Administered)226,Covaxin (Doses Administered)227,Covaxin (Doses Administered)228,Covaxin (Doses Administered)229,covaxindoses
1,AN,Andaman and Nicobar Islands,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0.0
2,AN,Andaman and Nicobar Islands,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0.0
3,AN,Andaman and Nicobar Islands,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,15.0
4,AP,Andhra Pradesh,0,0,0,0,0,0,0,0,...,303608,304302,308592,310250,318327,321354,322142,336748,342472,23283728.0
5,AP,Andhra Pradesh,0,0,0,0,0,0,0,0,...,407153,407658,414141,416476,425135,425591,432161,435991,436745,31925860.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
750,WB,West Bengal,0,0,0,0,0,0,0,0,...,128103,128264,128998,129481,129894,130277,130736,131656,132217,11444137.0
751,WB,West Bengal,0,0,0,0,0,0,0,0,...,69148,69487,70398,71027,71378,71645,71656,73758,74282,5539696.0
752,WB,West Bengal,0,0,0,0,0,0,0,0,...,168226,171396,174744,179212,180337,180440,182116,182402,182772,12033289.0
753,WB,West Bengal,NaN,0,0,0,0,0,0,0,...,118247,119050,120020,121980,123574,123585,124426,125243,126507,9702022.0
754,WB,West Bengal,0,0,0,0,0,0,0,0,...,135456,135831,137542,138023,138539,138641,139179,139763,140487,9758941.0

In [15]:
col_lista= list(val2)
col_lista.remove('State_Code')
col_lista.remove('State')
# col_lista

In [16]:
sum_frame_by_column(val2, 'covishielddoses', col_lista)

,State_Code,State,CoviShield (Doses Administered)1,CoviShield (Doses Administered)2,CoviShield (Doses Administered)3,CoviShield (Doses Administered)4,CoviShield (Doses Administered)5,CoviShield (Doses Administered)6,CoviShield (Doses Administered)7,CoviShield (Doses Administered)8,...,CoviShield (Doses Administered)221,CoviShield (Doses Administered)222,CoviShield (Doses Administered)223,CoviShield (Doses Administered)224,CoviShield (Doses Administered)225,CoviShield (Doses Administered)226,CoviShield (Doses Administered)227,CoviShield (Doses Administered)228,CoviShield (Doses Administered)229,covishielddoses
1,AN,Andaman and Nicobar Islands,0,0,0,1,1,2,3,206,...,30435,30447,30471,30513,30513,30513,30531,30541,30560,2632492.0
2,AN,Andaman and Nicobar Islands,0,0,0,0,0,33,244,390,...,101304,102005,102418,102624,103547,103572,104003,104433,104841,8231593.0
3,AN,Andaman and Nicobar Islands,23,23,42,88,123,204,305,324,...,214952,218109,220376,222486,224952,225225,226247,228279,229879,17408907.0
4,AP,Andhra Pradesh,287,504,778,1324,1969,2496,3302,4089,...,1855039,1868456,1912889,1925163,1988445,1999331,2000610,2086498,2128569,144107325.0
5,AP,Andhra Pradesh,424,1012,925,1798,2829,3859,4766,5964,...,2002714,2004394,2076072,2091505,2151201,2153150,2208567,2312890,2322388,160893339.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
750,WB,West Bengal,31,173,320,340,340,560,697,750,...,722797,724481,738504,757107,770196,778006,793225,807385,825595,62511512.0
751,WB,West Bengal,1,1,76,174,174,250,620,625,...,481825,488216,491782,498817,502637,505174,514527,530046,537875,42053477.0
752,WB,West Bengal,14,14,163,477,477,477,1343,1372,...,1762214,1787606,1808665,1834294,1871270,1890818,1910465,1985420,2023686,154103162.0
753,WB,West Bengal,NaN,0,101,287,287,477,1143,1174,...,659074,665132,670056,688688,688885,689808,708204,739324,746991,56164504.0
754,WB,West Bengal,62,62,142,324,451,705,1455,1542,...,1018323,1028943,1041281,1064851,1086077,1092506,1105581,1147366,1163385,82758186.0

In [17]:
finalstuff1 = val1[['State_Code','State','covaxindoses']].copy()
finalstuff2 = val2[['State_Code','State','covishielddoses']].copy()

In [18]:
result = pd.concat([finalstuff1, finalstuff2], axis=1, join='inner')

In [19]:
newresult = result[['State_Code','State','covaxindoses','covishielddoses']].copy()

In [20]:
newresult = newresult.loc[:,~newresult.columns.duplicated()]

In [21]:
findf = newresult.groupby(['State_Code','State']).sum().reset_index()
res = findf.copy(deep=True)

In [22]:
findf['vaccinationratio'] = findf['covishielddoses']/findf['covaxindoses']

In [23]:
findf = findf.drop(['covaxindoses','covishielddoses'],axis=1)

In [24]:
findf['State']=findf['State'].str.lower()

In [25]:
stufffindf = findf[['State_Code','vaccinationratio']].copy()

In [26]:
stufffindf.rename(columns = {'State_Code':'stateid'}, inplace = True)

In [27]:
# stufffindf['vaccinationratio'] = stufffindf['vaccinationratio'].apply(np.floor)

In [28]:
stufffindf.to_csv('vaccine-type-ratio-state.csv')

In [29]:
rawdata = pd.read_csv('cowin_vaccine_data_districtwise.csv',low_memory=False)

In [30]:
rawdata = rawdata.rename(columns=data.iloc[0])

In [31]:
rawdata = rawdata.drop(['S No','State_Code','State','Cowin Key'],axis=1)

In [32]:
rawdata = rawdata.rename(columns=rawdata.iloc[0])

In [33]:
thing = rawdata[['District_Key','Covaxin (Doses Administered)','CoviShield (Doses Administered)']].copy()

In [34]:
thing = thing.iloc[1:,:]

In [35]:
acols = []
count = 1
for column in thing.columns:
    if column == 'Covaxin (Doses Administered)':
        acols.append(f'Covaxin (Doses Administered){count}')
        count+=1
        continue
    acols.append(column)
thing.columns = acols
bcols = []
count = 1
for column in thing.columns:
    if column == 'Female(Individuals Vaccinated)':
        bcols.append(f'CoviShield (Doses Administered){count}')
        count+=1
        continue
    bcols.append(column)
thing.columns = bcols

In [36]:
bat1 = thing.filter(regex='Covaxin')
bat2 = thing.filter(regex='CoviShield')

In [37]:
stumps = thing[['District_Key']].copy()

In [38]:
sachin1 = pd.concat([stumps, bat1], axis=1)
sachin2 = pd.concat([stumps, bat2], axis=1)

In [39]:
column_list1= list(sachin1)
column_list1.remove('District_Key')
# col_list

In [40]:
sum_frame_by_column(sachin1, 'covaxindoses', column_list1)

,District_Key,Covaxin (Doses Administered)1,Covaxin (Doses Administered)2,Covaxin (Doses Administered)3,Covaxin (Doses Administered)4,Covaxin (Doses Administered)5,Covaxin (Doses Administered)6,Covaxin (Doses Administered)7,Covaxin (Doses Administered)8,Covaxin (Doses Administered)9,...,Covaxin (Doses Administered)221,Covaxin (Doses Administered)222,Covaxin (Doses Administered)223,Covaxin (Doses Administered)224,Covaxin (Doses Administered)225,Covaxin (Doses Administered)226,Covaxin (Doses Administered)227,Covaxin (Doses Administered)228,Covaxin (Doses Administered)229,covaxindoses
1,AN_Nicobars,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0.0
2,AN_North and Middle Andaman,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0.0
3,AN_South Andaman,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,15.0
4,AP_Anantapur,0,0,0,0,0,0,0,0,0,...,303608,304302,308592,310250,318327,321354,322142,336748,342472,23283728.0
5,AP_Chittoor,0,0,0,0,0,0,0,0,0,...,407153,407658,414141,416476,425135,425591,432161,435991,436745,31925860.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
750,WB_Purulia,0,0,0,0,0,0,0,0,0,...,128103,128264,128998,129481,129894,130277,130736,131656,132217,11444137.0
751,WB_Birbhum,0,0,0,0,0,0,0,0,0,...,69148,69487,70398,71027,71378,71645,71656,73758,74282,5539696.0
752,WB_South 24 Parganas,0,0,0,0,0,0,0,0,0,...,168226,171396,174744,179212,180337,180440,182116,182402,182772,12033289.0
753,WB_Uttar Dinajpur,NaN,0,0,0,0,0,0,0,0,...,118247,119050,120020,121980,123574,123585,124426,125243,126507,9702022.0
754,WB_Paschim Bardhaman,0,0,0,0,0,0,0,0,0,...,135456,135831,137542,138023,138539,138641,139179,139763,140487,9758941.0

In [41]:
column_list2= list(sachin2)
column_list2.remove('District_Key')
# col_lista

In [42]:
sum_frame_by_column(sachin2, 'covishielddoses', column_list2)

,District_Key,CoviShield (Doses Administered),CoviShield (Doses Administered),CoviShield (Doses Administered),CoviShield (Doses Administered),CoviShield (Doses Administered),CoviShield (Doses Administered),CoviShield (Doses Administered),CoviShield (Doses Administered),CoviShield (Doses Administered),...,CoviShield (Doses Administered),CoviShield (Doses Administered),CoviShield (Doses Administered),CoviShield (Doses Administered),CoviShield (Doses Administered),CoviShield (Doses Administered),CoviShield (Doses Administered),CoviShield (Doses Administered),CoviShield (Doses Administered),covishielddoses
1,AN_Nicobars,0,0,0,1,1,2,3,206,227,...,30435,30447,30471,30513,30513,30513,30531,30541,30560,6.028407e+08
2,AN_North and Middle Andaman,0,0,0,0,0,33,244,390,392,...,101304,102005,102418,102624,103547,103572,104003,104433,104841,1.885035e+09
3,AN_South Andaman,23,23,42,88,123,204,305,324,347,...,214952,218109,220376,222486,224952,225225,226247,228279,229879,3.986640e+09
4,AP_Anantapur,287,504,778,1324,1969,2496,3302,4089,4396,...,1855039,1868456,1912889,1925163,1988445,1999331,2000610,2086498,2128569,3.300058e+10
5,AP_Chittoor,424,1012,925,1798,2829,3859,4766,5964,6270,...,2002714,2004394,2076072,2091505,2151201,2153150,2208567,2312890,2322388,3.684457e+10
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
750,WB_Purulia,31,173,320,340,340,560,697,750,883,...,722797,724481,738504,757107,770196,778006,793225,807385,825595,1.431514e+10
751,WB_Birbhum,1,1,76,174,174,250,620,625,712,...,481825,488216,491782,498817,502637,505174,514527,530046,537875,9.630246e+09
752,WB_South 24 Parganas,14,14,163,477,477,477,1343,1372,1499,...,1762214,1787606,1808665,1834294,1871270,1890818,1910465,1985420,2023686,3.528962e+10
753,WB_Uttar Dinajpur,NaN,0,101,287,287,477,1143,1174,1285,...,659074,665132,670056,688688,688885,689808,708204,739324,746991,1.286167e+10
754,WB_Paschim Bardhaman,62,62,142,324,451,705,1455,1542,1622,...,1018323,1028943,1041281,1064851,1086077,1092506,1105581,1147366,1163385,1.895162e+10

In [43]:
lion1 = sachin1[['District_Key','covaxindoses']].copy()
lion2 = sachin2[['District_Key','covishielddoses']].copy()

In [44]:
mergedf = pd.concat([lion1, lion2], axis=1, join='inner')

In [45]:
newmergedf = mergedf.loc[:,~mergedf.columns.duplicated()].copy()

In [46]:
newmergedf['vaccinationratio'] = newmergedf['covishielddoses']/newmergedf['covaxindoses']

In [47]:
thenewmergedf = newmergedf[['District_Key','vaccinationratio']].copy()
finalnewmergedf = thenewmergedf[['District_Key','vaccinationratio']].copy()

In [48]:
finalthestuff = pd.merge(finalnewmergedf, stumps, how='inner', on=['District_Key'])

In [49]:
finalthestuff.drop_duplicates(subset ="District_Key",keep = 'first', inplace = True)

In [50]:
finalthestuff.rename(columns = {'District_Key':'districtid'}, inplace = True)

In [51]:
newarr = finalthestuff[['districtid','vaccinationratio']].copy()

In [52]:
import numpy as np

In [53]:
newarr['vaccinationratio'] =newarr['vaccinationratio'].apply(np.floor)

In [54]:
newarr.to_csv('vaccine-type-ratio-district.csv')

In [55]:
s_val1= val1['covaxindoses'].copy()
s_val2= val2['covishielddoses'].copy()

In [56]:
newVal1 = s_val1.to_frame()
newVal2 = s_val2.to_frame()

In [57]:
f_v = newVal1.sum(axis = 0, skipna = True)
s_v = newVal2.sum(axis = 0, skipna = True)

In [58]:
ro1 = pd.DataFrame(f_v)
ro2 = pd.DataFrame(s_v)

In [59]:
ro1=ro1.transpose()
ro2=ro2.transpose()

In [60]:
f_fin = pd.concat([ro1,ro2],axis=1)

In [61]:
f_fin['vaccineratio'] = f_fin['covishielddoses']/f_fin['covaxindoses']

In [62]:
f_fin.pop('covaxindoses')

0    5.606503e+09
Name: covaxindoses, dtype: float64

In [63]:
f_fin.pop('covishielddoses')

0    4.247116e+10
Name: covishielddoses, dtype: float64

In [64]:
f_fin['id'] = 'overall'

In [65]:
f_fin = f_fin[['id','vaccineratio']]

In [66]:
f_fin.to_csv('vaccine-type-ratio-overall.csv')